// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlGhH39EyJ0uqmI0Tak0CgUoiAb-sDGQI',
    appId: '1:447618325271:web:b5f6ebe18465f5779eb552',
    messagingSenderId: '447618325271',
    projectId: 'abc-notification-mobile',
    authDomain: 'abc-notification-mobile.firebaseapp.com',
    storageBucket: 'abc-notification-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ2aEusBr8Ql4mdileeU8T277EeSTGmAM',
    appId: '1:447618325271:android:52f84d6b424ec1459eb552',
    messagingSenderId: '447618325271',
    projectId: 'abc-notification-mobile',
    storageBucket: 'abc-notification-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7EU-ompKdwNZUK7U5R8QN0wFMiQ3B48Y',
    appId: '1:447618325271:ios:a802ddcdb6c677fe9eb552',
    messagingSenderId: '447618325271',
    projectId: 'abc-notification-mobile',
    storageBucket: 'abc-notification-mobile.appspot.com',
    iosClientId: '447618325271-of20ujna7ill1bsdatcrc41hr2lmic4o.apps.googleusercontent.com',
    iosBundleId: 'vn.com.abcsolutions.abcSafezoneDrtMobileApp',
  );
}
